<?php
use Zend\Form\Element;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">添加用户(新用户密码为 abc123456)</h3>
  </div>
  <div class="panel-body">
  
<?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<!-- 	<strong> Error </strong> The following errors have occurred:  -->
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>

<div id="searchContent"></div>

  		<?php 
  		$form = $this->form;
  		$form->prepare();
  		echo $this->form()->openTag($form);
  		?>
<fieldset>
		  <br/>
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">用户名:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('name');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">真实姓名:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('real_name');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
<!-- 		  <div class="form-group"> -->
<!-- 		    <label for="inputId" class="col-sm-2 control-label">Email:</label> -->
<!-- 		    <div class="col-sm-10"> -->
		    	<?php
// 				    $name = $form->get('email');
// 				    echo $this->formInput($name);
// 				?>
<!-- 		    </div> -->
<!-- 		  </div> -->
		  
<!-- 		  <div class="form-group"> -->
<!-- 		    <label for="inputId" class="col-sm-2 control-label">登录密码:</label> -->
<!-- 		    <div class="col-sm-10"> -->
		    	<?php
// 				    $name = $form->get('newPassword');
// 				    echo $this->formInput($name);
// 				?>
<!-- 		    </div> -->
<!-- 		  </div> -->
		  
<!-- 		  <div class="form-group"> -->
<!-- 		    <label for="inputId" class="col-sm-2 control-label">确认登录密码:</label> -->
<!-- 		    <div class="col-sm-10"> -->
		    	<?php
// 				    $name = $form->get('newConfirmPassword');
// 				    echo $this->formInput($name);
// 				?>
<!-- 				<span id="notSameSpan">两次密码不一致</span> -->
<!-- 		    </div> -->
<!-- 		  </div> -->
		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		  <?php echo $this->formElement($form->get('submit')) ?>&nbsp;<?php echo $this->formElement($form->get('cancel')) ?>
		  </div>
		  </div>		   	
		<?php echo $this->formElement($form->get('id')) ?>
</fieldset>		
		<?php echo $this->form()->closeTag() ?>
</div>
</div>
<script>
//  (function($){
// 	$(function(){
// 		$("#notSameSpan").hide();
// 		$("#user_form").submit(function(e){
// 			var newPassword = $.trim($("#newPassword").val());
// 			var newConfirmPassword = $.trim($("#newConfirmPassword").val());
// 			if(newPassword != "" && newConfirmPassword != ""){
// 				if(newPassword != newConfirmPassword){
// 					$("#notSameSpan").show();
// 					return false;
// 				}
// 			}
// 		});
// 	});
// })(jQuery);
</script>