<?php
use Zend\Form\Element;
use Test\Data;
use Admin\Model\Auth;
?>

<div class="panel panel-default">


      <div class="panel-body">
        <form name="search" class="form-inline" role="form" action="/news/list" method="get">
       
          <div class="form-group">
            <input value="<?php echo $this->param['title'];?>" type="text" name="title" class="form-control" id="title" placeholder="标题">
          </div>
          
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">是否删除:</div>
              <select class="form-control" name="is_delete" id="is_delete">
                <option value=1 <?if( $this->param['is_delete'] == 1){echo "selected";}?>>是</option>
                <option value=0 <?if( $this->param['is_delete'] == 0){echo "selected";}?>>否</option>
              </select>
            </div>
          </div>
          
<!--           <div class="form-group"> -->
           <!--   <input value="<?php echo $this->param['real_name'];?>" type="text" name="real_name" class="form-control" id="name" placeholder="真实姓名">-->
<!--           </div> -->
          
          <button type="submit" class="btn btn-primary">搜索</button>
          
          </form>
          </div>

  <div class="panel-body">
	<table class="table table-striped">
			<tr>
				<th>标题</th>
				<th>创建者</th>
				<th>开始时间</th>
				<th>状态</th>
				<th>操作</th>
				<?php 
				$verifyUrl = $this->url("default",array(
				    "controller"=>"news",
				    "action" => "verify"
				));
				$verfiy = false;
				if($this->CheckResource($verifyUrl)):
				    $verfiy = true;
				endif;
				if($verfiy):?>
				<th>审核</th>
				<?php
				endif;
				?>
			</tr> 
			 <?php foreach ($this->paginator as $news){ ?>
			<tr>
			    <td> <?php echo $this->escapehtml($news['title']); ?>  </td>
			    <td> <?php echo $this->escapehtml($this->GetUser($news['user_id'])['name']); ?> </td>
			    <td> <?php echo $this->escapehtml($news['start_date']); ?> </td>
			    <td>
			    	<?php 
			    	    if($news['status'] == 0):
			    	        echo "待审核";
			    	    elseif($news['status'] == 1):
			    	        echo "审核通过";
			    	    elseif($news['status'] == 2):
			    	        echo "审核未通过";
			    	    endif;
			    	?>
			    </td> 
			   
			    <td>
			    <?php 
			     $data = Data::getInstance();
			     $site = $data->get('site');
			     $newsUrl = "http://".$site['hostname']."/news/".$news['id']."?show=1";
			    ?>
			    <a target="_blank" href="<?=$newsUrl;?>">查看</a>&nbsp;&nbsp;
			    
			    <?php 
			         if($news['status'] != 1):
			    ?>
			    <a href="<?php echo $this->url("default",array(
			    		"controller"=>"news",
			    		"action" => "manage",
			    		"id" => $news['id']
			    )); ?>">编辑</a>&nbsp;&nbsp;
			    <?php 
			         endif;
			         $deleteUrl = $this->url("default",array(
			             "controller"=>"news",
			             "action" => "delete"
			         ));
			         if($this->CheckResource($deleteUrl)):
    			         if($news['is_delete'] == 0):
    			    ?>			    
    			    <a class="checkDeleteUrl" href="<?php echo $this->url("default",array(
    			    		"controller"=>"news",
    			    		"action" => "delete",
    			    		"id" => $news['id']
    			    )); ?>">删除</a>&nbsp;&nbsp;
    			    <?php
    			         endif;
        			    if($news['status'] == 1):
        			    ?>
        			    <a class="downProduct" href="<?php echo $this->url("default",array(
        			    		"controller"=>"news",
        			    		"action" => "resetVerify",
        			            "id" => $news['id']
        			    )); ?>">下架</a>&nbsp;&nbsp;
        			    <?php
        			         endif;
			    
			      
        			    if($news['is_delete'] == 1):
        			    ?>
        			    <a href="<?php echo $this->url("default",array(
        			    		"controller"=>"news",
        			    		"action" => "reactive",
        			            "id" => $news['id']
        			    )); ?>">取消删除</a>&nbsp;&nbsp;
        			    <?php 
        			     endif;
			         endif;
			         
			    ?>
			    </td>
			    <?php if($verfiy):?>
			    <td>
			    <?php 
			         if($news['status'] != 0):
			             echo "已审核";
			         else:
			     ?>
			    <a href="<?php echo $this->url("default",array(
			    		"controller"=>"news",
			    		"action" => "verify",
			    		"id" => $news['id']
			    )); ?>">审核通过</a>&nbsp;&nbsp;
			    
			    <a href="<?php echo $this->url("default",array(
			    		"controller"=>"news",
			    		"action" => "notVerify",
			    		"id" => $news['id']
			    )); ?>">审核未通过</a>&nbsp;&nbsp;
			    <?php 
			         endif;
			    ?>
			    </td>
			    <?php endif;?>
			</tr>
			<?php } ?>
	</table>
	
	<?php
        
	 	// add at the end of the file after the table
	 	try {
			echo $this->paginationControl(
			    // the paginator object
			    $this->paginator,
			    'sliding',
			    // the partial to use to render the control
			    array('partial/paginator.phtml', 'Admin'),
			    // the route to link to when a user clicks a control link
			    array("route"=>'default','route_params'=>array('controller'=>'news','action'=>'list'))
			);
		}catch (\Exception $e){
			echo $e->getMessage();
		}
	
	?>
</div>
</div>
