<?php
use Zend\Form\Element;
use Test\Data;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">添加新闻</h3>
  </div>
  <div class="panel-body">
  
<?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<!-- 	<strong> Error </strong> The following errors have occurred:  -->
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>

<div id="searchContent"></div>

  		<?php 
  		$form = $this->form;
  		$form->prepare();
  		echo $this->form()->openTag($form);
  		?>
<fieldset>
		  <br/>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">开始时间:</label>
			<div class="col-sm-10">
		    	<?php
				    $name = $form->get('start_date');
				    echo $this->formdate($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">标题:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('title');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">图片(列表):</label>
		    <div class="col-sm-10">
		    <input type="file" id="chooseImage" name="file">
		    <img id="cropedBigImg" <?php if($this->imagePath): echo "src=\"".$this->imagePath."\"";endif;?> value='custom' alt="请上传图片" data-address='' title="自定义背景"/>
		    </div>
		  </div>
		  
<!-- 		  <div class="form-group"> -->
<!-- 		    <label for="inputId" class="col-sm-2 control-label">图片(列表):</label> -->
<!-- 			<div class="col-sm-10"> -->
		    	<?php
// 				    $name = $form->get('image');
// 				    echo $this->formInput($name);
// 				?>
<!-- 		    </div> -->
<!-- 		  </div> -->
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">新闻描述:</label>
			<div class="col-sm-10">
		    	<?php
		    	     $name = $form->get('description');
		    	     echo $this->formtextarea($name);
				?>
		    </div>
		  </div>
		  <div class="form-group">
		  	
		    <label for="inputId" class="col-sm-2 control-label">内容:</label>
		    <div class="col-sm-10" style="width:50%;height:1000px;postion:relative;display:block">
		    	<?php
				    $name = $form->get('content');
				    echo $this->formtextarea($name);
				?>
		    </div>
		  </div>
		  		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		  <?php echo $this->formElement($form->get('id')) ?>
		  <?php echo $this->formElement($form->get('submit')) ?>&nbsp;<?php echo $this->formElement($form->get('cancel')) ?>
		  </div>
		  </div>		   	
</fieldset>		
		<?php echo $this->form()->closeTag() ?>
</div>
</div>


<script type="text/javascript" src="/scripts/admin/ckeditor/ckeditor.js">
</script>
<script type="text/javascript">
(function($){
	CKEDITOR.config.language = 'zh-cn';
	//CKEDITOR.config.toolbarCanCollapse = true;
// 	CKEDITOR.config.width = 'auto';
// 	CKEDITOR.config.height = 'auto';
	CKEDITOR.config.width = '1000';
	CKEDITOR.config.height = '900';
	<?php 
			   $data = Data::getInstance();
			   $site = $data->get('site');
			?>
	CKEDITOR.config.contentsCss = ['http://<?php echo $site['hostname'];?>/styles/common.css', 'http://<?php echo $site['hostname'];?>/styles/reset.css','http://<?php echo $site['hostname'];?>/styles/news.css']
	CKEDITOR.config.useComputedState = false
	CKEDITOR.config.fillEmptyBlocks = false;
	CKEDITOR.config.enterMode = CKEDITOR.ENTER_BR;
	CKEDITOR.config.shiftEnterMode = CKEDITOR.ENTER_P;
	CKEDITOR.config.tabSpaces = 0;
	CKEDITOR.config.startupMode = 'wysiwyg';
	CKEDITOR.config.toolbar_Full =
		[
			//{ name: 'document',		items : [ 'Source','-','Save','NewPage','DocProps','Preview','Print','-','Templates' ] },
			{ name: 'document',		items : [ 'Source'] },
			//{ name: 'tools',		items : [ 'Maximize', 'ShowBlocks','-','About' ] },
			//{ name: 'clipboard',	items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
			//{ name: 'editing',		items : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ] },
			//{ name: 'forms',		items : [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ] },
			{ name: 'basicstyles',	items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
			//{ name: 'paragraph',	items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
			{ name: 'paragraph',	items : [ 'CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
			{ name: 'links',		items : [ 'Link','Unlink','Anchor' ] },
			//{ name: 'insert',		items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ] },
			{ name: 'insert',		items : [ 'Image','Table'] },
			{ name: 'styles',		items : [ 'Styles','Format','Font','FontSize' ] },
			{ name: 'colors',		items : [ 'TextColor','BGColor' ] }

		];

	
	CKEDITOR.config.toolbar = 'Full';
	

	//CKEDITOR.config.format_div = { element : 'div', attributes : { 'class' : 'normalDiv' } };
	CKEDITOR.on( 'instanceReady', function( ev ){
	     with (ev.editor.dataProcessor.writer) {
	       setRules("p",  {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("h1", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("h2", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("h3", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("h4", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("h5", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("div", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("table", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("tr", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("td", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("iframe", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("li", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("ul", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	       setRules("ol", {indent : true, breakBeforeOpen : true, breakAfterOpen : true, breakBeforeClose : true, breakAfterClose : true} );
	     }
	})
})(jQuery)
</script>

<script>
 (function($){
	$(function(){
		CKEDITOR.replace("content");
	});
	
})(jQuery);

 $('#chooseImage').on('change',function(){
		var filePath = $(this).val();
		var fileFormat = filePath.substring(filePath.lastIndexOf(".")).toLowerCase();
		// 检查是否是图片
		if(fileFormat != '.png' && fileFormat != '.jpg' && fileFormat != '.jpeg') {
			$('#cropedBigImg').attr('src','');
			alert('上传错误,文件格式必须为：png/jpg/jpeg');
		    return;  
		}
		src = window.URL.createObjectURL(this.files[0]); //转成可以在本地预览的格式
	    $('#cropedBigImg').attr('src',src);
	});

	(function($){
		$(function(){
	 		$("#news_form").submit(function(e){
	 			var cropedBigImg = $.trim($("#cropedBigImg").attr('src'));
	 			if(cropedBigImg == ''){
					alert('请上传图片');
					return false;
	 	 		}
	 			var fileFormat = image.substring(image.lastIndexOf(".")).toLowerCase();
	 			// 检查是否是图片
	 			if(fileFormat != '.png' && fileFormat != '.jpg' && fileFormat != '.jpeg') {
	 				alert('上传错误,文件格式必须为：png/jpg/jpeg');
	 			    return false;  
	 			}
	 		});
		});
	})(jQuery);

</script>